### ISSUE TITLE
加入应用程序信息

### ISSUE THREAD

**Issue by darth30joker** [DoubleCiti/daimaduan.com#100]
包括:
- 当前程序的提交sha
- 页面的运行时间
- 服务器状态

**Comment by darth30joker** [comment]
移到v2.3里完成

**Comment by greatghoul** [comment]
这个感觉没有必要加，意义不大。

**Comment by darth30joker** [comment]
有逼格的网站都会有这个啊, 显示一下当前程序的版本号或build号, 再显示一下当前页面的加载时间.

你可以参考v2ex的底部

**Comment by greatghoul** [comment]
感觉实用就好。

**Comment by darth30joker** [comment]
至少要加入build版本号, 不然我都不知道部署的是哪个版本的代码了...

**Comment by darth30joker** [comment]
https://github.com/DoubleCiti/daimaduan.com/pull/217
