### ISSUE TITLE
根本没法注册啊?

### ISSUE THREAD

**Issue by suxiaogang** [DoubleCiti/daimaduan.com#104]
注册了页面刷新一下就没有然后了...

选择Github登录,callback之后跳转到绑定email的页面,那个input居然是只读的
机智的我赶紧用chrome dev tool把那行readonly删掉才注册成功的

**Comment by suxiaogang** [comment]
另外为了防止spammer建议把email在个人主页隐藏掉吧

**Comment by liul85** [comment]
`注册了页面刷新一下就没有然后了...`  是啥意思？

**Comment by darth30joker** [comment]
@Suxiaogang 使用第三方callback之后过来的页面, email确实是只读的, 因为这里不允许修改email地址

不过不修改email地址有什么问题吗?

**Comment by suxiaogang** [comment]
@liul85 就是没提示成功,也没提示失败,页面还是这个页面
但用这个账号登陆时,提示用户名密码错误,应该就是没有注册成功

@david-xie 明白你的意思,因为Github的openid回调里有email对吧?
但是email没有回填到这个input框啊,而页面又有email的校验,所以没法继续注册啊~

**Comment by darth30joker** [comment]
@Suxiaogang 那就证明这里出了问题, 正确逻辑下, email是应该能拿到并填入input框的.

将此问题标记为bug, 稍后修复

**Comment by liul85** [comment]
@Suxiaogang 因为现在程序比较简单，注册发送email还没有修改为异步操作，当你点了注册之后，会有一些延时等待，然后页面才会返回结果。在返回结果之前不要刷新页面。

**Comment by darth30joker** [comment]
@Suxiaogang 你的问题在于你在github上没有填email地址, 所以oauth验证完以后, 没有拿到email地址...

**Comment by darth30joker** [comment]
@Suxiaogang 另外, 加入gdgxian.slack.com, 里面有一个daimaduan-dev的频道, 可以参与更多讨论

**Comment by darth30joker** [comment]
问题解决: https://github.com/DoubleCiti/daimaduan.com/pull/112

**Comment by darth30joker** [comment]
@Suxiaogang 马上就会部署到产品环境上了
