### ISSUE TITLE
是否应该抛弃disqus?

### ISSUE THREAD

**Issue by darth30joker** [DoubleCiti/daimaduan.com#119]
使用disqus确实很方便, 但是也带来了一些问题.

最大的问题是, 当用户登录网站后, 他并没有同时登录disqus, 如果他要同时对代码集合做出评论的话, 又要登录disqus, 这一步其实很繁琐.

所以我们是否需要写一个自己的评论系统呢?

**Comment by yaodong** [comment]
You may integrate Disqus with your own user system. Better than maintenance one all by yourself. 

FYI
- [Single Sign-On](https://help.disqus.com/customer/portal/articles/1104796)

**Comment by darth30joker** [comment]
@yaodong 你说的是没错了, 可是毕竟是两个用户管理系统

**Comment by darth30joker** [comment]
集成了disqus的SSO, 现在用户在网站登陆后, 会自动登陆disqus了

https://github.com/DoubleCiti/daimaduan.com/pull/126
