### ISSUE TITLE
改进部署代码

### ISSUE THREAD

**Issue by darth30joker** [DoubleCiti/daimaduan.com#142]
1. 修改部署后的检查, 要能查看返回的status code是不是200
2. 要定期删除过期的部署代码
3. 有回滚功能
4. 最好能加入服务器的停止和启动功能

**Comment by greatghoul** [comment]
现在的部署流程是怎么的？

之前在 rails 里面，一般都是每次部署，都是在一个临时的文件夹中进行更新，安装依赖，编译 assets 之类的操作，只有最后一步，才映射新版本到 current 版本。

**Comment by darth30joker** [comment]
@greatghoul https://github.com/DoubleCiti/daimaduan.com/blob/master/fabfile.py#L48

**Comment by darth30joker** [comment]
https://github.com/DoubleCiti/daimaduan.com/pull/150

@greatghoul 有空review一下
