### ISSUE TITLE
切换回pygments?

### ISSUE THREAD

**Issue by darth30joker** [DoubleCiti/daimaduan.com#160]

**Comment by darth30joker** [comment]
@greatghoul 我们要切到pygments的原因是什么来着?

我想把这个问题讨论清楚, 分析好利弊再做决定

**Comment by greatghoul** [comment]
highlightjs 的渲染很慢，而且嵌入脚本到别的网站时，不好加一个依赖，所以使用的 pygments，所以干脆都用它吧。

**Comment by darth30joker** [comment]
👌
那就切到pygments上吧

**Comment by darth30joker** [comment]
https://github.com/DoubleCiti/daimaduan.com/pull/178
