### ISSUE TITLE
port to Python 3

### ISSUE THREAD

**Issue by yaodong** [DoubleCiti/daimaduan.com#258]
我觉得应该用 Python 3。

**Comment by darth30joker** [comment]
@yaodong 不用Python3的原因是很多依赖包对Py3的支持并不是很好, 有的干脆就不支持, 所以没有办法升级到Py3

**Comment by yaodong** [comment]
那能不能整理一份这些包的列表呢？

**Comment by yaodong** [comment]
3 out of those 3 have no direct dependencies blocking their transition
- fabric
- flask-log
- mongoengine

**Comment by wujunze** [comment]
我也感觉应该用py3.5

**Comment by darth30joker** [comment]
upyun的包同样依赖于2.x, 没有3的包
