### ISSUE TITLE
如果用户没有在duoshuo注册过, 它的头像就取不到了

### ISSUE THREAD

**Issue by darth30joker** [DoubleCiti/daimaduan.com#45]
应该有默认图片, 如果用户没有注册的话, 显式默认头像

![dxie_-_](https://cloud.githubusercontent.com/assets/100747/10931941/3ae9a01a-8307-11e5-9dd7-871d7e5e8f8f.png)

**Comment by greatghoul** [comment]
多说也封闭了，改用 cn.gavatar.com 吧，这个没有墙是可以访问到的。

**Comment by darth30joker** [comment]
晕死, 多说也会被封啊...

2015-11-05 8:30 GMT+08:00 greatghoul notifications@github.com:

> 多说也封闭了，改用 cn.gavatar.com 吧，这个没有墙是可以访问到的。
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/DoubleCiti/daimaduan.com/issues/45#issuecomment-153914987
> .

## 

---

Best Regards,
David Xie
Founder of ScriptFan technology community - http://scriptfan.com
Manager of Xi'an GDG (Google Developer Group)
http://about.me/davidx

---

Everything happens for a reason. Attitude determines everything!

**Comment by darth30joker** [comment]
fixed in https://github.com/DoubleCiti/daimaduan.com/pull/50
