### ISSUE TITLE
code和paste没有title的时候, 我们默认给什么呢?

### ISSUE THREAD

**Issue by darth30joker** [DoubleCiti/daimaduan.com#5]
我以前的做法是, 如果没有写title, 那么就写"没有标题". 我刚才看了一下gist, 它们写的是"gist:ID_FOR_THIS_PASTE".

我们要怎么做比较好呢? 这里是肯定需要一个标题的, 不能为空的.

你有什么建议吗?

**Comment by greatghoul** [comment]
`没有标题` 就好了。

**Comment by darth30joker** [comment]
可以, 我们先加这个试着
