### ISSUE TITLE
邮件没有正确发送

### ISSUE THREAD

**Issue by darth30joker** [DoubleCiti/daimaduan.com#78]
@liul85 你测试过发邮件吗? 我现在注册了用户, 没有收到邮件.

**Comment by greatghoul** [comment]
> 请激活您在代码段注册的邮箱地址再进行操作!

我是在你开发邮件之前注册的，提示这个，但我没有收到邮件，应该需要一个重新发送验证邮件的入口。

@liul85

**Comment by darth30joker** [comment]
@greatghoul 对, 确实需要这个功能

目前你可以通过访问`/send_mail/<your email address`来重新发送

**Comment by liul85** [comment]
这个暂时不考虑吧 上线后用户注册后都会发邮件的。在注册后跳转的结果页面会给提示 如果没收到可以重新发送。

**Comment by liul85** [comment]
这里也要限制一下，用户只能给自己重发验证email

**Comment by darth30joker** [comment]
@liul85 这里面是有问题的. 说一个case, 比如说用户注册了, 你发送邮件了, 然后他没有收到, 但是他把这个页面关了, 下次再回到代码段后, 哪里有地方让他重新发送邮件呢?

所以这里建议改为, 用户访问需要验证的页面, 发现没有权限, 错误信息里加一个连接, `重新发送验证邮件`

**Comment by liul85** [comment]
行 我把这个记录下来。改一下。

**Comment by yaodong** [comment]
"重新发送邮件" 这个操作，不应该是 GET 请求。GET 请求不应该有副作用。

**Comment by yaodong** [comment]
"重新发送邮件" 这个操作，不应该是 GET 请求。

问题有以下：
- GET 请求不能有副作用。
- 没有检查是否已经激活，造成重复发送。
- 在任意站点构造 resend url，然后放到 img url 即可触发此站点的邮件发送。
- 使用 GET 请求，email 在 URL 中会导致 email 的泄漏，更何况没有启用 HTTPS。

**Comment by darth30joker** [comment]
@liul85 能够按照yaodong提的建议, 相应的改一下呢?

**Comment by liul85** [comment]
好 我查一下资料把这块修改一下。

**Comment by darth30joker** [comment]
https://github.com/DoubleCiti/daimaduan.com/pull/132
