### ISSUE TITLE
将评分改为喜欢

### ISSUE THREAD

**Issue by greatghoul** [DoubleCiti/daimaduan.com#86]
评分会给用户压力，像我就比较不喜欢评分，twitter 最近也将收藏改为喜欢了。

这里我准备将评论改为喜欢，另外单独加一个收藏功能，模式比较类似 Pintreast。

用户可以建立不同的收藏夹，然后可以把代码添加到收藏夹中，这样找喜欢也比较方便。

**Comment by greatghoul** [comment]
![](http://greatghoul.b0.upaiyun.com/1512/kxmpxTvy1Xcv1.png)

大概做了下效果图， @liul85  @david-xie 觉得这样如何？

**Comment by liul85** [comment]
我喜欢这个 😄

**Comment by darth30joker** [comment]
@greatghoul 非常好看! 就要这个了!

**Comment by darth30joker** [comment]
https://github.com/DoubleCiti/daimaduan.com/issues/86
